# Version
app:
  version: 1.0.0
  config: CONFIG-1.0

# RabbitMQ properties for configuration refresh    
spring:
  rabbitmq:
    host: hr-rabbit
    port: 5672
    username: guest
    password: guest   
