# Common Properties
spring:
  application:
    name: student-service

server:
  port: 8300

# Eureka Properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8500/eureka

  instance:
    hostname: localhost
