# DB properties

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

# Custom Configs
student:
  type: Commerce
