# Common Properties
spring:
  application:
    name: zuul-service

server:
  port: 8600

# Eureka Properties
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8500/eureka

  instance:
    hostname: localhost      

# Zuul Properties    
zuul:
  prefix: /api
  routes:
    school-service:
      path: /school-service/**
      service-id:  SCHOOL-SERVICE
    student-service:
      path: /student-service/**
      service-id: STUDENT-SERVICE
